# Generated by Django 3.0.7 on 2020-08-08 18:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('repository_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('link_to_project', models.CharField(blank=True, max_length=10000, null=True)),
                ('about_project', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/dav1d/Desktop/projects/django/project_qada/portfolio/static/portfolio/'), upload_to='')),
                ('categories', models.ManyToManyField(to='portfolio.Category')),
                ('used_technologies', models.ManyToManyField(to='portfolio.Skill')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('short_bio', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('nationality', models.CharField(default='Georgian', max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('awards_won', models.IntegerField(default=0)),
                ('facebook_profile', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram_profile', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter_profile', models.CharField(blank=True, max_length=1000, null=True)),
                ('github_profile', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/dav1d/Desktop/projects/django/project_qada/portfolio/static/portfolio/'), upload_to='')),
                ('languages', models.ManyToManyField(to='portfolio.Language')),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
