# Generated by Django 3.0.7 on 2020-09-24 11:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=60)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(max_length=100000)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/dav1d/Desktop/projects/django/project_qada/portfolio/static/portfolio/'), upload_to='')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
