# Generated by Django 3.0.7 on 2020-09-24 11:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='placeholder_image',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/dav1d/Desktop/projects/django/project_qada/portfolio/static/portfolio/'), upload_to=''),
            preserve_default=False,
        ),
    ]
