# Generated by Django 3.0.7 on 2020-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blogpost_placeholder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(default='development', max_length=100),
            preserve_default=False,
        ),
    ]
