# Generated by Django 3.0.7 on 2020-09-28 19:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blogpost_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='something', storage=django.core.files.storage.FileSystemStorage(location='/home/dav1d/Desktop/projects/django/project_qada/portfolio/static/portfolio/'), upload_to=''),
            preserve_default=False,
        ),
    ]
