# Generated by Django 3.0.7 on 2020-09-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200928_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
