# Generated by Django 3.0.7 on 2020-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_title', models.CharField(max_length=200)),
                ('en_title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('background_image', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(max_length=100000)),
                ('film_link_low', models.CharField(max_length=100000)),
                ('film_link_high', models.CharField(max_length=100000)),
                ('film_poster_low', models.CharField(max_length=100000)),
                ('film_poster_high', models.CharField(max_length=100000)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
