# Generated by Django 3.0.7 on 2020-07-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200712_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
