# Generated by Django 3.0.7 on 2020-07-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200712_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='en_title',
            field=models.CharField(max_length=200),
        ),
    ]
