# Generated by Django 3.0.7 on 2020-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200712_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='en_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='geo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
