# Generated by Django 3.0.7 on 2020-07-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200712_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('background_image', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, max_length=100000, null=True)),
                ('film_poster_low', models.CharField(max_length=100000)),
                ('film_poster_high', models.CharField(max_length=100000)),
                ('genres', models.ManyToManyField(blank=True, to='movies.Genre')),
            ],
            options={
                'db_table': 'serie',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('episode_link_low', models.CharField(max_length=100000)),
                ('episode_link_high', models.CharField(max_length=100000)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Serie')),
            ],
            options={
                'db_table': 'episode',
            },
        ),
    ]
